# Generated by Django 5.1.3 on 2024-12-03 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('league_management', '0003_match_teams'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='season',
            options={'ordering': ['-year']},
        ),
    ]
